# Generated by Django 5.0.7 on 2024-08-13 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='number_of_product',
            new_name='quantity',
        ),
    ]
