# Generated by Django 5.0.7 on 2024-08-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_number_of_product_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_of_product',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
