# Generated by Django 5.0.7 on 2024-08-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='return',
            name='reason_of_return',
        ),
        migrations.RemoveField(
            model_name='return',
            name='user',
        ),
        migrations.AddField(
            model_name='return',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
